### ISSUE TITLE
Add DynamoDB database to stack to store voting information

### ISSUE THREAD

**Issue by NinteMars** [Allen-BME/pointless-analogies#11]
A DynamoDB database should be added to the stack to store voting information.

I think, at least for now, that the database can be set up like
Partition key: Image ID/key  // *Look at chapter07/gallery which created a hash for each*

We will likely need to add a sort key that associates to a unique voter so we can check to see if someone already voted, but we can probably wait on that for now

**Comment by samuelstanley0101** [comment]
I think we should make this into an RDS database, since with voting information we want the data to be 100% correct. We can do that with a DynamoDB if we have a queue and some additional logic, but since RDS already does that for us I figure that's what we should probably use.

**Comment by NinteMars** [comment]
Likely needed information:
Key /ID: varchar(whatever size our hash output is) → Image ID to link to image in bucket
Category1: varchar(30 should be plenty
Category1VoteCount: int
Category2: varchar(3)
Category2VoteCount: int

If we ever plan on adding support for comments, we would likely need an additional database, as we couldn't implement an arbitrary amount of comments in the table with SQl.

**Comment by samuelstanley0101** [comment]
I've created the database within the stack. The next step is to create a lambda function to create the table with the given categories.

**Comment by samuelstanley0101** [comment]
The database has been pushed to the rds-database branch. It is feature complete, but the table isn't created correctly because of dependency issues.

**Comment by samuelstanley0101** [comment]
Switched back to DynamoDB, table is complete and merged. There's also a function to put initial data in, which currently uses test data.
