### ISSUE TITLE
Add "upload image" button to main page / index

### ISSUE THREAD

**Issue by NinteMars** [Allen-BME/pointless-analogies#14]
An upload images button should be added to the top of the page on the index/index lambda. There should be a check to see that there is only one uploaded file, and that the file is an image (reducing allowed types to .png and .jpeg would probably be good).

Doing a quick look, it looks like this will best be handled with a bit of JavaScript on the main page that calls a lambda function that adds the image to the bucket. Utilizing only a lambda might bring some scalability concerns and would be rather slow.

**Comment by NinteMars** [comment]
The uploaded image should also be renamed to be a randomly generated hash, so we can link the image in the bucket to the image in the RDS database

**Comment by Allen-BME** [comment]
finished
