### ISSUE TITLE
Add buttons to vote for category

### ISSUE THREAD

**Issue by NinteMars** [Allen-BME/pointless-analogies#23]
There should be two buttons underneath each image. When the button is clicked, the vote count for that category should be incremented. Because we don't have time to implement accounts, a user can increment an image multiple times. You could potentially try to avoid this by getting device info from a request, and only allowing a device to vote on each image once, but only try to do so once the basic functionality is added, and we have the time.

**Comment by samuelstanley0101** [comment]
These buttons are now implemented through query string parameters of an HTTP API Gateway endpoint.
