### ISSUE TITLE
Create test script for uploading images to S3 bucket

### ISSUE THREAD

**Issue by NinteMars** [Allen-BME/pointless-analogies#3]
It may be helpful for testing purposes, since the webapp will start with zero images, to have a small script that would upload a few images to the database to test web app function and layout.

**Comment by NinteMars** [comment]
This could also potentially include adding vote counts to the DynamoDB database at some point

**Comment by Allen-BME** [comment]
I'll try this out

**Comment by Allen-BME** [comment]
I'll wait to close this until the script is tested. I'll test it the next time we deploy

**Comment by Allen-BME** [comment]
I'm realizing it won't work as it is now. I still need to figure out how to give the full S3 bucket name created by CloudFormation to the script.

**Comment by NinteMars** [comment]
Reopened since the script needs to be updated to use the new bucket name

**Comment by Allen-BME** [comment]
script was updated to include new bucket name
