### ISSUE TITLE
Create list of categories

### ISSUE THREAD

**Issue by NinteMars** [Allen-BME/pointless-analogies#4]
We should start creating a list of categories for our analogies. We can start with a text file listing each, before moving towards finalizing how we want to use our database and figuring out how we want to automatically populate it.

I think ~20 categories will be fine, at least initially, due to the low amount of users while having each image categories being different enough.

**Comment by NinteMars** [comment]
Because of how short the category list will likely be, and since I think randomly picking from a database might be more complicated, maybe we just hardcode the list into a lambda function that returns a random category?

Though, we would likely need to explain how this would scale

**Comment by cambrosini555** [comment]
I added a list of categories in a lambda file. One is randomly selected from the 20

**Comment by NinteMars** [comment]
Want to leave open, since the lambda should probably be defined like the other lambda function, and needs to be added to the CDK stack
