### ISSUE TITLE
Reduce number of categories for images from previously agreed upon 4 to 2

### ISSUE THREAD

**Issue by NinteMars** [Allen-BME/pointless-analogies#5]
I personally believe that we might want to have two categories for each image instead of four
- I think that it would require us to come up with more categories, as having four would lead to significantly higher chances of repeats
- I feel that if we have four, it is significantly more likely that 1-2 of the categories will just be "obvious" nos, which can sort of defeat the purpose of the whole game. Limiting categories to two I think forces more of a discussion

**Comment by Allen-BME** [comment]
I agree, I'm fine with moving back to 2.

**Comment by NinteMars** [comment]
The number of categories has been reduced to 2
